import type { PrismaClient } from '@prisma/client'
import { type Routine, RoutineExecutionType } from '@web-scraper/common'

export async function seedRoutine(prisma: PrismaClient) {
  await prisma.routine.create({
    data: {
      name: 'Example routine',
      description: 'Example routine generated by seeding database',
      stopOnError: true,
      executionPlan: JSON.stringify({
        type: RoutineExecutionType.SPECIFIC_IDS,
        dataSourceName: 'Example',
        ids: [1],
      } satisfies Routine['executionPlan']),
    },
  })

  await prisma.routineProcedureRelation.create({ data: { routineId: 1, procedureId: 1 } })
}
