export enum ErrorCode {
  NO_ERROR = 0,
  UNKNOWN_ERROR = 1,

  API_ERROR = 100,
  DATABASE_ERROR = 101,
  INCORRECT_DATA = 102,
  ENTRY_ALREADY_EXISTS = 103,

  ACTION_CANCELLED_BY_USER = 200,

  NOT_FOUND = 404,
}
