name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint project
      run: npm run lint

    - name: Typecheck project
      run: npm run typecheck

    - name: Build project
      run: npm run build

    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome

    - name: Run tests
      run: npm run test 
      env:
        CI: true