name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          DISABLE_ERD: true

      - name: Check code with linter
        run: yarn run lint

      - name: Generate and seed database
        run: yarn run db:generate:reset
        env:
          DISABLE_ERD: true

      - name: Build all projects
        run: yarn run build
        env:
          DISABLE_ERD: true

      - name: Run all tests
        run: yarn run test:ci
        env:
          CI: true
