import type { Meta, StoryObj } from '@storybook/react'
import { ExecutionStepper } from './ExecutionStepper'
import type { ParsedScraperExecution } from './helpers'

const executionMock = [
  {
    start: {
      id: '58bd8a1b-9d0c-43d5-986c-ddd93f925cb6',
      event: 'scraperExecutionStarted',
      scope: 'routine',
      routine: {
        id: 1,
        name: 'Example routine',
        description: 'Example routine generated by seeding database',
        stopOnError: true,
        procedures: [
          {
            id: 1,
            name: 'Get title from example site',
            startUrl: '{{URL.ORIGIN}}',
            waitFor: 'body > div:nth-child(1) > h1',
            siteInstructionsId: 1,
            type: 'dataRetrieval',
            flow: {
              id: 3,
              globalReturnValues: [],
              actionName: 'action.Get title',
              onSuccess: {
                id: 1,
                globalReturnValues: [],
                actionName: 'global.finishProcedure',
                onSuccess: null,
                onFailure: null,
              },
              onFailure: {
                id: 2,
                globalReturnValues: [],
                actionName: 'global.finishProcedureWithError',
                onSuccess: null,
                onFailure: null,
              },
            },
          },
        ],
        executionPlan: {
          type: 'specificIds',
          dataSourceName: 'Example',
          ids: [1],
        },
      },
      iterationIndex: 0,
    },
    result: {
      id: '58bd8a1b-9d0c-43d5-986c-ddd93f925cb6',
      event: 'scraperExecutionResult',
      scope: 'routine',
      routineResult: {
        routine: {
          id: 1,
          name: 'Example routine',
          description: 'Example routine generated by seeding database',
          stopOnError: true,
          procedures: [
            {
              id: 1,
              name: 'Get title from example site',
              startUrl: '{{URL.ORIGIN}}',
              waitFor: 'body > div:nth-child(1) > h1',
              siteInstructionsId: 1,
              type: 'dataRetrieval',
              flow: {
                id: 3,
                globalReturnValues: [],
                actionName: 'action.Get title',
                onSuccess: {
                  id: 1,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedure',
                  onSuccess: null,
                  onFailure: null,
                },
                onFailure: {
                  id: 2,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedureWithError',
                  onSuccess: null,
                  onFailure: null,
                },
              },
            },
          ],
          executionPlan: {
            type: 'specificIds',
            dataSourceName: 'Example',
            ids: [1],
          },
        },
        source: {
          dataSource: {
            name: 'Example',
            columns: [
              {
                name: 'Title',
                type: 'TEXT',
              },
              {
                name: 'Timestamp',
                type: 'INTEGER',
              },
              {
                name: 'Custom',
                type: 'TEXT',
              },
            ],
          },
          item: {
            id: 1,
            data: [
              {
                columnName: 'Title',
                value: 'Example Domain',
              },
              {
                columnName: 'Timestamp',
                value: 1714692232,
              },
              {
                columnName: 'Custom',
                value: 'Custom value from siteInstructions seed',
              },
            ],
          },
        },
        proceduresExecutionResults: [
          {
            procedure: {
              id: 1,
              name: 'Get title from example site',
              startUrl: '{{URL.ORIGIN}}',
              waitFor: 'body > div:nth-child(1) > h1',
              siteInstructionsId: 1,
              type: 'dataRetrieval',
              flow: {
                id: 3,
                globalReturnValues: [],
                actionName: 'action.Get title',
                onSuccess: {
                  id: 1,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedure',
                  onSuccess: null,
                  onFailure: null,
                },
                onFailure: {
                  id: 2,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedureWithError',
                  onSuccess: null,
                  onFailure: null,
                },
              },
            },
            flowExecutionResult: {
              flow: {
                id: 3,
                globalReturnValues: [],
                actionName: 'action.Get title',
                onSuccess: {
                  id: 1,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedure',
                  onSuccess: null,
                  onFailure: null,
                },
                onFailure: {
                  id: 2,
                  globalReturnValues: [],
                  actionName: 'global.finishProcedureWithError',
                  onSuccess: null,
                  onFailure: null,
                },
              },
              flowStepsResults: [
                {
                  flowStep: {
                    id: 3,
                    globalReturnValues: [],
                    actionName: 'action.Get title',
                  },
                  actionResult: {
                    action: {
                      id: 1,
                      name: 'Get title',
                      url: '{{URL.ORIGIN}}',
                      siteInstructionsId: 1,
                      actionSteps: [
                        {
                          id: 1,
                          orderIndex: 1,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Title',
                            saveDataType: 'elementContent',
                            saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                          },
                        },
                        {
                          id: 2,
                          orderIndex: 2,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                        {
                          id: 3,
                          orderIndex: 3,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Timestamp',
                            saveDataType: 'currentTimestamp',
                          },
                        },
                        {
                          id: 4,
                          orderIndex: 4,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                        {
                          id: 5,
                          orderIndex: 5,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Custom',
                            saveDataType: 'custom',
                            saveToDataSourceValue: 'Custom value from siteInstructions seed',
                          },
                        },
                        {
                          id: 6,
                          orderIndex: 6,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                      ],
                    },
                    actionStepsResults: [
                      {
                        step: {
                          id: 1,
                          orderIndex: 1,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Title',
                            saveDataType: 'elementContent',
                            saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                      {
                        step: {
                          id: 2,
                          orderIndex: 2,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                      {
                        step: {
                          id: 3,
                          orderIndex: 3,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Timestamp',
                            saveDataType: 'currentTimestamp',
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                      {
                        step: {
                          id: 4,
                          orderIndex: 4,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                      {
                        step: {
                          id: 5,
                          orderIndex: 5,
                          actionId: 1,
                          type: 'saveToDataSource',
                          data: {
                            dataSourceQuery: 'DataSource.Example.Custom',
                            saveDataType: 'custom',
                            saveToDataSourceValue: 'Custom value from siteInstructions seed',
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                      {
                        step: {
                          id: 6,
                          orderIndex: 6,
                          actionId: 1,
                          type: 'wait',
                          data: {
                            duration: 5000,
                          },
                        },
                        result: {
                          errorType: 'error.common.noError',
                        },
                      },
                    ],
                  },
                  returnedValues: [],
                  succeeded: true,
                },
                {
                  flowStep: {
                    id: 1,
                    globalReturnValues: [],
                    actionName: 'global.finishProcedure',
                  },
                  actionResult: null,
                  returnedValues: [],
                  succeeded: true,
                },
              ],
            },
          },
        ],
      },
      iterationIndex: 0,
    },
    finish: {
      id: '58bd8a1b-9d0c-43d5-986c-ddd93f925cb6',
      event: 'scraperExecutionFinished',
      scope: 'routine',
      iterationIndex: 0,
    },
  },
  {
    start: {
      id: '5217a5ea-c016-4bab-9383-2f740822de01',
      event: 'scraperExecutionStarted',
      scope: 'procedure',
      procedure: {
        id: 1,
        name: 'Get title from example site',
        startUrl: '{{URL.ORIGIN}}',
        waitFor: 'body > div:nth-child(1) > h1',
        siteInstructionsId: 1,
        type: 'dataRetrieval',
        flow: {
          id: 3,
          globalReturnValues: [],
          actionName: 'action.Get title',
          onSuccess: {
            id: 1,
            globalReturnValues: [],
            actionName: 'global.finishProcedure',
            onSuccess: null,
            onFailure: null,
          },
          onFailure: {
            id: 2,
            globalReturnValues: [],
            actionName: 'global.finishProcedureWithError',
            onSuccess: null,
            onFailure: null,
          },
        },
      },
    },
    result: {
      id: '5217a5ea-c016-4bab-9383-2f740822de01',
      event: 'scraperExecutionResult',
      scope: 'procedure',
      procedureResult: {
        flow: {
          id: 3,
          globalReturnValues: [],
          actionName: 'action.Get title',
          onSuccess: {
            id: 1,
            globalReturnValues: [],
            actionName: 'global.finishProcedure',
            onSuccess: null,
            onFailure: null,
          },
          onFailure: {
            id: 2,
            globalReturnValues: [],
            actionName: 'global.finishProcedureWithError',
            onSuccess: null,
            onFailure: null,
          },
        },
        flowStepsResults: [
          {
            flowStep: {
              id: 3,
              globalReturnValues: [],
              actionName: 'action.Get title',
            },
            actionResult: {
              action: {
                id: 1,
                name: 'Get title',
                url: '{{URL.ORIGIN}}',
                siteInstructionsId: 1,
                actionSteps: [
                  {
                    id: 1,
                    orderIndex: 1,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Title',
                      saveDataType: 'elementContent',
                      saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                    },
                  },
                  {
                    id: 2,
                    orderIndex: 2,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                  {
                    id: 3,
                    orderIndex: 3,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Timestamp',
                      saveDataType: 'currentTimestamp',
                    },
                  },
                  {
                    id: 4,
                    orderIndex: 4,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                  {
                    id: 5,
                    orderIndex: 5,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Custom',
                      saveDataType: 'custom',
                      saveToDataSourceValue: 'Custom value from siteInstructions seed',
                    },
                  },
                  {
                    id: 6,
                    orderIndex: 6,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                ],
              },
              actionStepsResults: [
                {
                  step: {
                    id: 1,
                    orderIndex: 1,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Title',
                      saveDataType: 'elementContent',
                      saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
                {
                  step: {
                    id: 2,
                    orderIndex: 2,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
                {
                  step: {
                    id: 3,
                    orderIndex: 3,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Timestamp',
                      saveDataType: 'currentTimestamp',
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
                {
                  step: {
                    id: 4,
                    orderIndex: 4,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
                {
                  step: {
                    id: 5,
                    orderIndex: 5,
                    actionId: 1,
                    type: 'saveToDataSource',
                    data: {
                      dataSourceQuery: 'DataSource.Example.Custom',
                      saveDataType: 'custom',
                      saveToDataSourceValue: 'Custom value from siteInstructions seed',
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
                {
                  step: {
                    id: 6,
                    orderIndex: 6,
                    actionId: 1,
                    type: 'wait',
                    data: {
                      duration: 5000,
                    },
                  },
                  result: {
                    errorType: 'error.common.noError',
                  },
                },
              ],
            },
            returnedValues: [],
            succeeded: true,
          },
          {
            flowStep: {
              id: 1,
              globalReturnValues: [],
              actionName: 'global.finishProcedure',
            },
            actionResult: null,
            returnedValues: [],
            succeeded: true,
          },
        ],
      },
    },
    finish: {
      id: '5217a5ea-c016-4bab-9383-2f740822de01',
      event: 'scraperExecutionFinished',
      scope: 'procedure',
    },
  },
  {
    start: {
      id: 'e07b8990-830b-4225-9c5f-d9953bbb08e2',
      event: 'scraperExecutionStarted',
      scope: 'flow',
      flow: {
        id: 3,
        globalReturnValues: [],
        actionName: 'action.Get title',
        onSuccess: {
          id: 1,
          globalReturnValues: [],
          actionName: 'global.finishProcedure',
          onSuccess: null,
          onFailure: null,
        },
        onFailure: {
          id: 2,
          globalReturnValues: [],
          actionName: 'global.finishProcedureWithError',
          onSuccess: null,
          onFailure: null,
        },
      },
    },
    result: {
      id: 'e07b8990-830b-4225-9c5f-d9953bbb08e2',
      event: 'scraperExecutionResult',
      scope: 'flow',
      flowResult: [
        {
          flowStep: {
            id: 3,
            globalReturnValues: [],
            actionName: 'action.Get title',
          },
          actionResult: {
            action: {
              id: 1,
              name: 'Get title',
              url: '{{URL.ORIGIN}}',
              siteInstructionsId: 1,
              actionSteps: [
                {
                  id: 1,
                  orderIndex: 1,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Title',
                    saveDataType: 'elementContent',
                    saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                  },
                },
                {
                  id: 2,
                  orderIndex: 2,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
                {
                  id: 3,
                  orderIndex: 3,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Timestamp',
                    saveDataType: 'currentTimestamp',
                  },
                },
                {
                  id: 4,
                  orderIndex: 4,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
                {
                  id: 5,
                  orderIndex: 5,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Custom',
                    saveDataType: 'custom',
                    saveToDataSourceValue: 'Custom value from siteInstructions seed',
                  },
                },
                {
                  id: 6,
                  orderIndex: 6,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
              ],
            },
            actionStepsResults: [
              {
                step: {
                  id: 1,
                  orderIndex: 1,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Title',
                    saveDataType: 'elementContent',
                    saveToDataSourceValue: 'body > div:nth-child(1) > h1',
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
              {
                step: {
                  id: 2,
                  orderIndex: 2,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
              {
                step: {
                  id: 3,
                  orderIndex: 3,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Timestamp',
                    saveDataType: 'currentTimestamp',
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
              {
                step: {
                  id: 4,
                  orderIndex: 4,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
              {
                step: {
                  id: 5,
                  orderIndex: 5,
                  actionId: 1,
                  type: 'saveToDataSource',
                  data: {
                    dataSourceQuery: 'DataSource.Example.Custom',
                    saveDataType: 'custom',
                    saveToDataSourceValue: 'Custom value from siteInstructions seed',
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
              {
                step: {
                  id: 6,
                  orderIndex: 6,
                  actionId: 1,
                  type: 'wait',
                  data: {
                    duration: 5000,
                  },
                },
                result: {
                  errorType: 'error.common.noError',
                },
              },
            ],
          },
          returnedValues: [],
          succeeded: true,
        },
        {
          flowStep: {
            id: 1,
            globalReturnValues: [],
            actionName: 'global.finishProcedure',
          },
          actionResult: null,
          returnedValues: [],
          succeeded: true,
        },
      ],
    },
    finish: {
      id: 'e07b8990-830b-4225-9c5f-d9953bbb08e2',
      event: 'scraperExecutionFinished',
      scope: 'flow',
    },
  },
  {
    start: {
      id: '9e15a086-e149-41e6-b98d-f852bd834693',
      event: 'scraperExecutionStarted',
      scope: 'action',
      action: {
        id: 1,
        name: 'Get title',
        url: '{{URL.ORIGIN}}',
        siteInstructionsId: 1,
        actionSteps: [
          {
            id: 1,
            orderIndex: 1,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Title',
              saveDataType: 'elementContent',
              saveToDataSourceValue: 'body > div:nth-child(1) > h1',
            },
          },
          {
            id: 2,
            orderIndex: 2,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
          {
            id: 3,
            orderIndex: 3,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Timestamp',
              saveDataType: 'currentTimestamp',
            },
          },
          {
            id: 4,
            orderIndex: 4,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
          {
            id: 5,
            orderIndex: 5,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Custom',
              saveDataType: 'custom',
              saveToDataSourceValue: 'Custom value from siteInstructions seed',
            },
          },
          {
            id: 6,
            orderIndex: 6,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
        ],
      },
    },
    result: {
      id: '9e15a086-e149-41e6-b98d-f852bd834693',
      event: 'scraperExecutionResult',
      scope: 'action',
      actionResult: [
        {
          step: {
            id: 1,
            orderIndex: 1,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Title',
              saveDataType: 'elementContent',
              saveToDataSourceValue: 'body > div:nth-child(1) > h1',
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
        {
          step: {
            id: 2,
            orderIndex: 2,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
        {
          step: {
            id: 3,
            orderIndex: 3,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Timestamp',
              saveDataType: 'currentTimestamp',
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
        {
          step: {
            id: 4,
            orderIndex: 4,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
        {
          step: {
            id: 5,
            orderIndex: 5,
            actionId: 1,
            type: 'saveToDataSource',
            data: {
              dataSourceQuery: 'DataSource.Example.Custom',
              saveDataType: 'custom',
              saveToDataSourceValue: 'Custom value from siteInstructions seed',
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
        {
          step: {
            id: 6,
            orderIndex: 6,
            actionId: 1,
            type: 'wait',
            data: {
              duration: 5000,
            },
          },
          result: {
            errorType: 'error.common.noError',
          },
        },
      ],
    },
    finish: {
      id: '9e15a086-e149-41e6-b98d-f852bd834693',
      event: 'scraperExecutionFinished',
      scope: 'action',
    },
  },
  {
    start: {
      id: '0925260a-e34e-4d3a-b6fa-d29035ce1690',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 1,
        orderIndex: 1,
        actionId: 1,
        type: 'saveToDataSource',
        data: {
          dataSourceQuery: 'DataSource.Example.Title',
          saveDataType: 'elementContent',
          saveToDataSourceValue: 'body > div:nth-child(1) > h1',
        },
      },
    },
    result: {
      id: '0925260a-e34e-4d3a-b6fa-d29035ce1690',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: '0925260a-e34e-4d3a-b6fa-d29035ce1690',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: '70b5ec53-2cca-418e-b5e4-13c902bd2a8a',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 2,
        orderIndex: 2,
        actionId: 1,
        type: 'wait',
        data: {
          duration: 5000,
        },
      },
    },
    result: {
      id: '70b5ec53-2cca-418e-b5e4-13c902bd2a8a',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: '70b5ec53-2cca-418e-b5e4-13c902bd2a8a',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: 'ab611ae3-c8ad-4724-a558-4fa857f1c265',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 3,
        orderIndex: 3,
        actionId: 1,
        type: 'saveToDataSource',
        data: {
          dataSourceQuery: 'DataSource.Example.Timestamp',
          saveDataType: 'currentTimestamp',
        },
      },
    },
    result: {
      id: 'ab611ae3-c8ad-4724-a558-4fa857f1c265',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: 'ab611ae3-c8ad-4724-a558-4fa857f1c265',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: '2e14319c-f642-4c1a-abcc-543c61687172',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 4,
        orderIndex: 4,
        actionId: 1,
        type: 'wait',
        data: {
          duration: 5000,
        },
      },
    },
    result: {
      id: '2e14319c-f642-4c1a-abcc-543c61687172',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: '2e14319c-f642-4c1a-abcc-543c61687172',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: '81839321-753a-4048-93f4-1bc4e6d50a7f',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 5,
        orderIndex: 5,
        actionId: 1,
        type: 'saveToDataSource',
        data: {
          dataSourceQuery: 'DataSource.Example.Custom',
          saveDataType: 'custom',
          saveToDataSourceValue: 'Custom value from siteInstructions seed',
        },
      },
    },
    result: {
      id: '81839321-753a-4048-93f4-1bc4e6d50a7f',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: '81839321-753a-4048-93f4-1bc4e6d50a7f',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: '84b3e43c-1f69-4481-ba97-5029884fc84a',
      event: 'scraperExecutionStarted',
      scope: 'actionStep',
      actionStep: {
        id: 6,
        orderIndex: 6,
        actionId: 1,
        type: 'wait',
        data: {
          duration: 5000,
        },
      },
    },
    result: {
      id: '84b3e43c-1f69-4481-ba97-5029884fc84a',
      event: 'scraperExecutionResult',
      scope: 'actionStep',
      actionStepResult: {
        errorType: 'error.common.noError',
      },
    },
    finish: {
      id: '84b3e43c-1f69-4481-ba97-5029884fc84a',
      event: 'scraperExecutionFinished',
      scope: 'actionStep',
    },
  },
  {
    start: {
      id: '23915132-068c-4c08-9e09-ccc486f4f113',
      event: 'scraperExecutionStarted',
      scope: 'flow',
      flow: {
        id: 1,
        globalReturnValues: [],
        actionName: 'global.finishProcedure',
        onSuccess: null,
        onFailure: null,
      },
    },
    result: {
      id: '23915132-068c-4c08-9e09-ccc486f4f113',
      event: 'scraperExecutionResult',
      scope: 'flow',
      flowResult: [
        {
          flowStep: {
            id: 1,
            globalReturnValues: [],
            actionName: 'global.finishProcedure',
          },
          actionResult: null,
          returnedValues: [],
          succeeded: true,
        },
      ],
    },
    finish: {
      id: '23915132-068c-4c08-9e09-ccc486f4f113',
      event: 'scraperExecutionFinished',
      scope: 'flow',
    },
  },
] as ParsedScraperExecution[]

const meta = {
  title: 'Scraper execution/ExecutionStepper',
  component: ExecutionStepper,
  parameters: { layout: 'centered' },
  args: {
    execution: executionMock,
  },
} satisfies Meta<typeof ExecutionStepper>

export default meta
type Story = StoryObj<typeof meta>

export const Horizontal: Story = {
  args: { orientation: 'horizontal' },
}

export const Vertical: Story = {
  args: { orientation: 'vertical' },
}
